CREATE TABLE #PAIS
(
ID_PAIS INT PRIMARY KEY IDENTITY (1,1),
NOME_PAIS VARCHAR (100) UNIQUE NOT NULL,
COTINENTI VARCHAR (100) NOT NULL
)

CREATE TABLE #ESTADO
(
ID_ESTADO INT PRIMARY KEY IDENTITY (1,1),
NOME_ESTADO VARCHAR (100) NOT NULL,
UF CHAR (2),
ID_PAIS INT FOREIGN KEY REFERENCES #PAIS (ID_PAIS)
)

CREATE TABLE #CIDADE
(
ID_CIDADE INT PRIMARY KEY IDENTITY (1,1),
NOME_CIDADE VARCHAR (100) NOT NULL,
RENDA DECIMAL (18,4),
ID_ESTADO INT FOREIGN KEY REFERENCES #ESTADO (ID_ESTADO)
)
ALTER TABLE #CIDADE
DROP COLUMN RENDA  
ALTER TABLE #CIDADE
ADD DATA_REGISTRO DATETIME DEFAULT GETDATE()

INSERT INTO #PAIS 
(NOME_PAIS,COTINENTI)
VALUES
('BRASIL','AMÉRICA DO SUL'),
('INDIA','ÁSIA')

INSERT INTO #ESTADO
(NOME_ESTADO,UF,ID_PAIS)
VALUES
('SÃO PAULO','SP',1),
('BAHIA','BA',1),
('MAHARASHTRA',NULL,2)

INSERT INTO #CIDADE (NOME_CIDADE,ID_ESTADO)
VALUES
('MARILIA',1),
('SALVADOR',2),
('BOMBAI',3)
